### ISSUE TITLE
bug(gatsby-plugin-fastify): Server function throws 'stream.on is not a function' after being called.

### ISSUE THREAD

**Issue by JosueGalRe** [gatsby-uc/plugins#472]
## Describe the bug

Hi, I'm trying to use the server functions with the plugin for fastify. The server starts fine and the assets are provided correctly, however, the moment I try to access a server function, the log provided below appears.

I have attached a code sandbox link that reproduces the issue. The issue is present starting Gatsby 5.12.1 (probably 5.12.0 too, but I'm unable to make it work with that version). 

## To Reproduce

https://codesandbox.io/p/devbox/runtime-smoke-5dzn6k

1. Run `pnpm run clean`
2. Run `pnpm run build`
3. Run `pnpm run start`
4. Access a server function using the endpoint
5. Check logs:

```
{"level":30,"time":1709324331653,"pid":81635,"hostname":"SV5BHFC63","msg":"Logging Level set @ info"}
{"level":30,"time":1709324331654,"pid":81635,"hostname":"SV5BHFC63","msg":"Mounting Gatsby @ /"}
{"level":30,"time":1709324331663,"pid":81635,"hostname":"SV5BHFC63","msg":"Gatsby 500 error page missing, using generic 500 error for DSG/SSR"}
{"level":30,"time":1709324331671,"pid":81635,"hostname":"SV5BHFC63","msg":"Registering 2 function(s)"}
{"level":30,"time":1709324337695,"pid":81635,"hostname":"SV5BHFC63","msg":"Registering 0 client-only route(s)"}
{"level":30,"time":1709324337697,"pid":81635,"hostname":"SV5BHFC63","msg":"Registering 0 redirect(s)"}
{"level":30,"time":1709324337700,"pid":81635,"hostname":"SV5BHFC63","msg":"Registering 0 reverse proxy route(s)"}
{"level":30,"time":1709324337703,"pid":81635,"hostname":"SV5BHFC63","msg":"Gatsby 404 error page exists"}
{"level":30,"time":1709324337879,"pid":81635,"hostname":"SV5BHFC63","msg":"Server listening at http://127.0.0.1:8080"}
{"level":30,"time":1709324341918,"pid":81635,"hostname":"SV5BHFC63","reqId":"req-1","req":{"method":"POST","url":"/api/verify","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":37700},"msg":"incoming request"}
{"level":50,"time":1709324341934,"pid":81635,"hostname":"SV5BHFC63","err":{"type":"TypeError","message":"stream.on is not a function","stack":"TypeError: stream.on is not a function\n    at readStream (/home/bgaldamez/**/**/.cache/functions/verify.js:28093:10)\n    at getRawBody (/home/bgaldamez/**/**/.cache/functions/verify.js:28005:12)\n    at read (/home/bgaldamez/**/**/.cache/functions/verify.js:4404:3)\n    at Array.jsonParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4673:5)\n    at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)\n    at Array.urlencodedParser (/home/bgaldamez/**/**/.cache/functions/verify.js:5120:7)\n    at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)\n    at Array.textParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4969:7)\n    at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)\n    at Array.rawParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4858:7)\n    at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)\n    at Array.multerMiddleware (/home/bgaldamez/**/**/.cache/functions/verify.js:25602:41)\n    at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)\n    at functionWrapper (/home/bgaldamez/**/**/.cache/functions/verify.js:9687:5)\n    at Object.handler (/home/bgaldamez/**/**/node_modules/.pnpm/gatsby-plugin-fastify@0.13.3_fastify@4.26.1_gatsby@5.13.3_graphql@16.8.1/node_modules/gatsby-plugin-fastify/dist/plugins/functions.js:42:39)\n    at preHandlerCallback (/home/bgaldamez/**/**/node_modules/.pnpm/fastify@4.26.1/node_modules/fastify/lib/handleRequest.js:137:37)"},"msg":"stream.on is not a function"}
{"level":30,"time":1709324341945,"pid":81635,"hostname":"SV5BHFC63","reqId":"req-1","res":{"statusCode":500},"responseTime":26.500499999150634,"msg":"request completed"}
```

```
TypeError: stream.on is not a function
at readStream (/home/bgaldamez/**/**/.cache/functions/verify.js:28093:10)
at getRawBody (/home/bgaldamez/**/**/.cache/functions/verify.js:28005:12)
at read (/home/bgaldamez/**/**/.cache/functions/verify.js:4404:3)
at Array.jsonParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4673:5)
at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)
at Array.urlencodedParser (/home/bgaldamez/**/**/.cache/functions/verify.js:5120:7)
at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)
at Array.textParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4969:7)
at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)
at Array.rawParser (/home/bgaldamez/**/**/.cache/functions/verify.js:4858:7)
at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)
at Array.multerMiddleware (/home/bgaldamez/**/**/.cache/functions/verify.js:25602:41)
at runMiddlewareOrFunction (/home/bgaldamez/**/**/.cache/functions/verify.js:9682:25)
at functionWrapper (/home/bgaldamez/**/**/.cache/functions/verify.js:9687:5)
at Object.handler (/home/bgaldamez/**/**/node_modules/.pnpm/gatsby-plugin-fastify@0.13.3_fastify@4.26.1_gatsby@5.13.3_graphql@16.8.1/node_modules/gatsby-plugin-fastify/dist/plugins/functions.js:42:39)
at preHandlerCallback (/home/bgaldamez/**/**/node_modules/.pnpm/fastify@4.26.1/node_modules/fastify/lib/handleRequest.js:137:37)
```

The problematic line in the output file is the following:

```js
/**
 * Read the data from the stream.
 *
 * @param {object} stream
 * @param {string} encoding
 * @param {number} length
 * @param {number} limit
 * @param {function} callback
 * @public
 */

function readStream (stream, encoding, length, limit, callback) {
  // code {...}

  // attach listeners
  stream.on('aborted', onAborted) // <- Here
  stream.on('close', cleanup)
  stream.on('data', onData)
  stream.on('end', onEnd)
  stream.on('error', onEnd)

  // more code {...}
}
```

## Expected behavior

The server function should be executed as expected.

## System Info

System:
    OS: Linux 5.15 Ubuntu 23.10 23.10 (Mantic Minotaur) # (WSL 2)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.11.1 - /tmp/yarn--1709318664802-0.3033425562973491/node # have tried with node v18.19.1 too
    Yarn: 1.22.21 - /tmp/yarn--1709318664802-0.3033425562973491/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm # (pnpm)
  npmPackages:
    gatsby: ^5.13.3 => 5.13.3
    gatsby-plugin-client-side-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-fastify: ^0.13.3 => 0.13.3
    gatsby-plugin-google-tagmanager: ^5.13.1 => 5.13.1
    gatsby-plugin-hubspot: ^2.0.0 => 2.0.0
    gatsby-plugin-image: ^3.13.1 => 3.13.1
    gatsby-plugin-manifest: ^5.13.1 => 5.13.1
    gatsby-plugin-postcss: ^6.13.1 => 6.13.1
    gatsby-plugin-react-svg: ^3.3.0 => 3.3.0
    gatsby-plugin-root-import: ^2.0.9 => 2.0.9
    gatsby-plugin-sharp: ^5.13.1 => 5.13.1
    gatsby-plugin-sitemap: ^6.13.1 => 6.13.1
    gatsby-plugin-styled-components: ^6.13.1 => 6.13.1
    gatsby-plugin-tailwindcss: ^1.0.3 => 1.0.3
    gatsby-source-filesystem: ^5.13.1 => 5.13.1
    gatsby-source-wordpress: ^7.13.3 => 7.13.3
    gatsby-transformer-sharp: ^5.13.1 => 5.13.1

**Comment by JosueGalRe** [comment]
Closing this as I managed to identify the faulty library. Sorry for the inconvenience!

**Comment by JosueGalRe** [comment]
Actually I managed to recreate the issue in a code sandbox, I'll attach it here:
https://codesandbox.io/p/devbox/runtime-smoke-5dzn6k

**Comment by JosueGalRe** [comment]
Just tested and the last working version is 5.11.0; 5.12.0 doesn't works at all and 5.12.1 has this issue.

**Comment by moonmeister** [comment]
Hey @JosueGalRe, I'm not putting any effort into this plugin. It needs to be replaced with the new Gatsby Adapters spec. That's been started but not finished. Don't have a lot of time atm. You're welcome to contribute to that or contribute a fix for this.
